spring:
      application:
                  name: FACULTY-SERVICE
                  
eureka:
      client:
            register-with-eureka: true
            fetch-registery:  true
            service-url:  
                      default-zone: http://localhost:8761/eureka/
      instance:
              hostname: localhost